Clean up GCHP config file runConfig.sh
 - Adds to documentation in the file
 - Reorders configurables so that most frequently changed settings
   are first.
 - Add logical toggle for auto-update of diagnostic collections so
   that it can be easily turned off.

Signed-off-by: Lizzie Lundgren <elundgren@seas.harvard.edu>

diff --git a/run/GCHP/runConfig.sh.template b/run/GCHP/runConfig.sh.template
--- a/run/GCHP/runConfig.sh.template
+++ b/run/GCHP/runConfig.sh.template
@@ -8,8 +8,40 @@
 #
 # Initial version: E. Lundgren, 8/17/2017
 
+###############################################################
+#
+# Contents of this file:
+#
+#    FREQUENTLY CHANGED SETTINGS (***customize your run here***)
+#       - Compute resources (num nodes, num cores
+#       - Run grid resolution
+#       - Simulation start, end, duration
+#       - Initial restart file
+#       - Optionfor more frequent output restart files
+#       - Turn components on/off
+#       - Diagnostic frequency, duration, and monthly mean
+#       - Debug print options (informational only)
+#
+#    LESS FREQUENTLY CHANGED SETTINGS
+#      - timesteps
+#      - dust mass tuning factor
+#      - manual configuration of domain decomposition
+#
+#    ERROR CHECKS
+# 
+#    UTILITY FUNCTIONS TO UPDATE CONFIG FILES
+#
+#    COMMANDS TO UPDATE CONFIG FILES
+#
+###############################################################
+
+
+########################################
+#     FREQUENTLY CHANGED SETTINGS
+########################################
+
 #------------------------------------------------
-#   Compute Resources
+#   Compute resources
 #------------------------------------------------
 TOTAL_CORES={TotalCores}
 NUM_NODES={NumNodes}
@@ -20,40 +52,7 @@ NUM_CORES_PER_NODE={NumCoresPerNode}
 # resources available.
 
 #------------------------------------------------
-#   Domain decomposition
-#------------------------------------------------
-NXNY_AUTO=ON
-NX=1 # Ignore if NXNY_AUTO=ON
-NY=6 # Ignore if NXNY_AUTO=ON
-# Cores are distributed across each of the six cubed sphere faces using
-# configurable parameters NX and NY. Each face is divided into NX by NY/6
-# regions and each of those regions is processed by a single core 
-# independent of which node it belongs to. Making NX by NY/6 as square
-# as possible reduces communication overhead in GCHP.
-#
-# Set NXNY_AUTO to either auto-calculate NX and NY (ON) (recommended)
-# or set them manually (OFF).
-
-# Rules and tips for setting NX and NY manually (NXNY_AUTO=OFF):
-#   1. NY must be an integer and a multiple of 6	  
-#   2. NX*NY must equal total number of cores (NUM_NODES*NUM_CORES_PER_NODE)
-#   3. Choose NX and NY to optimize NX x NY/6 squareness 
-#         Good examples: (NX=4,NY=24)  -> 96  cores at 4x4
-#                        (NX=6,NY=24)  -> 144 cores at 6x4
-#         Bad examples:  (NX=8,NY=12)  -> 96  cores at 8x2
-#                        (NX=12,NY=12) -> 144 cores at 12x2
-#   4. Domain decomposition requires that CS_RES/NX >= 4 and CS_RES*6/NY >= 4,
-#      which puts an upper limit on total cores per grid resolution.
-#         c24: 216 cores   (NX=6,  NY=36 )
-#         c48: 864 cores   (NX=12, NY=72 )
-#         c90: 3174 cores  (NX=22, NY=132)
-#        c180: 12150 cores (NX=45, NY=270)
-#        c360: 48600 cores (NX=90, NY=540)
-#      Using fewer cores may still trigger a domain decomposition error, e.g.:
-#         c48: 768 cores   (NX=16, NY=48)  --> 48/16=3 will trigger FV3 error
-
-#------------------------------------------------
-#   Internal Cubed Sphere Resolution
+#   Run grid resolution
 #------------------------------------------------
 CS_RES={GridRes}
 STRETCH_GRID=OFF
@@ -68,106 +67,54 @@ TARGET_LON=170.0
 #    (3) Target lon must be in range [0,360)
 
 #------------------------------------------------
-#    Simulation Start, End, Duration, # runs
+#    Simulation start, end, duration
 #------------------------------------------------
 Start_Time="{DATE1} {TIME1}"
 End_Time="{DATE2} {TIME2}"
 Duration="{dYYYYMMDD} {dHHmmss}"
-Num_Runs=1
 #
-# The simplest run is a single segment run (Num_Runs=1). For this case
-# duration should be less than or equal to the difference between start
+# Duration should be less than or equal to the difference between start
 # and end time. If end time is past start time plus duration, the simulation
 # will end at start time plus duration rather than end time.
 #
-# Setting duration such that two or more durations can occur between start
-# and end will enable multi-segmented runs. At the end of each run the 
-# end time is stored as the new start time in output file cap_restart.
-# Rerunning without removing or editing cap_restart will start at the
-# start time in cap_restart rather than the start time set here. 
-# Use this feature with the multi-segmented runs, what we call the
-# multi-run option. Use this option as follows:
-#
-#   1. Set Num_Runs to total # of consecutive runs
-#   2. Set durationto the duration of each INDIVIDUAL run
-#   3. Set end date after start date to span ALL runs
-#   4. Copy gchp.multirun.sh and gchp.multirun.run from runScriptSamples/
-#      to run directory
-#   5. Configure resources at the top of gchp.multirun.run (assumes SLURM).
-#      This is the run script used for each individual run in the sequence.
-#      It is important to use this since it contains necessary automatic
-#      updates such as using the output restart file from one run as the
-#      input restart file in the next.
-#   6. Execute shell script gchp.multirun.sh at the command line
-#         $ ./gchp.multirun.sh
-#
+# At the end of each run the end time is stored as the new start time
+# in output file cap_restart. Rerunning without removing or editing
+# cap_restart will start at the start time in cap_restart rather than
+# the start time set here. Beware of this feature - if you do not want to
+# do consecutive runs then delete cap_restart prior to running. If you 
+# do want to run consecutive simulations you can make use of this feature in
+# your own custom run scripts.
+
 #------------------------------------------------
-#    Initial Restart File
+#    Initial restart file
 #------------------------------------------------
 INITIAL_RESTART=initial_GEOSChem_rst.c${CS_RES}_{SIMULATION}.nc
-
+#
 # By default the linked restart files in the run directories will be 
-# used. Please note that HEMCO restart variables are stored in the same
+# used. You can specify a custom initial restart file by overwriting the
+# default above.
+#
+# Please note that HEMCO restart variables are stored in the same
 # restart file as species concentrations. Initial restart files available 
-# on gcgrid do not contain HEMCO variables which will have the same effect
-# as turning the HEMCO restart file option off in GC classic. However, all 
-# output restart files will contain HEMCO restart variables for your next run.
-# You can specify a custom initial restart file by overwriting the default.
+# do NOT contain HEMCO variables. Using them will have the same effect
+# as turning the HEMCO restart file option off in GC classic.
+# However, all output restart files will contain HEMCO restart variables
+# for your next run.
 
-#------------------------------------------------------------
-#    Turn Components On/Off
-#------------------------------------------------------------
-# WARNING: these settings will override manual updates you make to config files!
-# input.geos
-Turn_on_Chemistry=T
-Turn_on_Dry_Deposition=T
-Turn_on_Wet_Deposition=T
-Turn_on_Transport=T
-Turn_on_Cloud_Conv=T
-Turn_on_PBL_Mixing=T
-Turn_on_Non_Local_Mixing=T
-# HEMCO_Config.rc
-Turn_on_Base_Emissions=true
-
-#------------------------------------------------
-#    Timesteps
-#------------------------------------------------
-if [[ $CS_RES -lt 180 ]]; then
-    ChemEmiss_Timestep_sec=1200
-    TransConv_Timestep_sec=600
-    TransConv_Timestep_HHMMSS=001000
-else
-    ChemEmiss_Timestep_sec=600
-    TransConv_Timestep_sec=300
-    TransConv_Timestep_HHMMSS=000500
-fi
-RRTMG_Timestep_sec=10800
-# Optimal timesteps are dependent on grid resolution and are automatically
-# set based on the GCHP Working Group's recommendation below. To override
-# these settings, comment out the code and manually define the following
-# variables:
-#    ChemEmiss_Timestep_sec     : chemistry timestep interval [s]
-#    TransConv_Timestep_sec     : dynamic timestep interval [s]
-#    TransConv_Timestep_HHMMSS  : dynamic timestep interval as HHMMSS string
-#
-# WARNING: Settings in this file will override settings in input.geos!
-#
-# NOTE: Default timesteps for c24 and c48, the cubed-sphere rough equivalents
-# of 4x5 and 2x2.5, are the same as defaults timesteps in GEOS-Chem Classic
-
-#------------------------------------------------
-#    Output Restarts
-#------------------------------------------------
+#-------------------------------------------------
+#    Option for more frequent output restart files
+#-------------------------------------------------
 Periodic_Checkpoint=OFF
 Checkpoint_Freq="1680000"
 Checkpoint_Ref_Date=START
 Checkpoint_Ref_Time=START
-# You can output restart files at regular or irregular intervals throughout
-# your simulation. These restarts are in addition to the end-of-run restart
-# which is always produced. To turn on periodic checkpoints, set
-# Period_Checkpoint to ON; set to OFF to disable.
+# An end-of-run restart file is always produced by GCHP. Optionally, you
+# can also output restart files at regular or irregular intervals throughout
+# your simulation. To turn on periodic checkpoints, set above setting
+# Periodic_Checkpoint to ON; set to OFF to disable. Then follow instructions
+# below for regular or irregular output frequency.
 #
-# To configure regular checkpoint files:
+# Regular output frequency:
 #  - Set Checkpoint_Freq to a string of format HHmmss. More than 2 digits for
 #    hours string is permitted, e.g. 168000 for 7 days.
 #  - Set Checkpoint_Ref_Date and Checkpoint_Ref_Date to START to use the run
@@ -176,17 +123,35 @@ Checkpoint_Ref_Time=START
 #    file will be output the first timestep. That happens before setting the
 #    values from the restart files so it will contain all zeros.
 #
-# To configure irregular checkpoint files:
+# Irregular output frequency:
 #  - Set Checkpoint_Freq to string of space-separated zeros with each zero
-#    corresponding to a single checkpoint file (e.g. 0 0 0 for 3 checkpoints total)
+#    corresponding to a single checkpoint file (e.g. 0 0 0 for 3 checkpoints
+#    total)
 #  - Set Checkpoint_Ref_Date to a string of space-separated YYYYMMDD values.
 #  - Set Checkpoint_Ref_Time to a string of space-separated HHmmss values.
-#  - WARNING: There is currently a limit of 9 irregular checkpoint values.
 
-#------------------------------------------------
-#    Output Diagnostics
-#------------------------------------------------        
-timeAvg_monthly="{AvgMonthly}" # 0 (off) or 1 (on)
+#------------------------------------------------------------
+#    Turn components on/off
+#------------------------------------------------------------
+# WARNING: these settings will override manual updates you make to config files!
+#
+# input.geos:
+Turn_on_Chemistry=T
+Turn_on_Dry_Deposition=T
+Turn_on_Wet_Deposition=T
+Turn_on_Transport=T
+Turn_on_Cloud_Conv=T
+Turn_on_PBL_Mixing=T
+Turn_on_Non_Local_Mixing=T
+#
+# HEMCO_Config.rc:
+Turn_on_Base_Emissions=true
+
+#---------------------------------------------------------------------
+#    Diagnostic frequency, duration, and monthly mean
+#---------------------------------------------------------------------
+AutoUpdate_Diagnostics=ON
+timeAvg_monthly="{AvgMonthly}"
 timeAvg_freq="{AvgFreq}"
 timeAvg_dur="{AvgDur}"
 timeAvg_collections=(SpeciesConc    \
@@ -225,26 +190,57 @@ inst_collections=(ConcAboveSfc      \
 #   Duration  = frequency of diagnostic file  write (HHmmSS)
 # 
 # NOTES: 
-#  1. If monthly is enabled then frequency and duration are ignored
-#  1. Freq and duration hours may exceed 2 digits, e.g. 7440000 for 31 days
-#  2. Collections excluded from the lists must be manually set in HISTORY.rc
-#  3. To turn off collections comment them out in HISTORY.rc, not here.
+#  1. Set AutoUpdate_Diagnostics to ON/OFF to toggle auto-update of HISTORY.rc
+#  2. If monthly is enabled then frequency and duration are ignored
+#  3. Freq and duration hours may exceed 2 digits, e.g. 7440000 for 31 days
+#  4. Collections excluded from the lists must be manually set in HISTORY.rc
+#  5. To turn off collections comment them out in HISTORY.rc, not here.
 
-#------------------------------------------------
-#    Debug Options
-#------------------------------------------------
-# Run-time debug options in config files are not set from this file.
-# Try the following manually instead to enable debug prints:
+#-----------------------------------------------------
+#    Run-time debug print options (informational only)
+#-----------------------------------------------------
+# Run-time debug options in config files are no longer set from this file.
+# Do the following manually instead to enable debug prints:
 #   (1) GEOS-Chem core: Set "Turn on debug printout?" to T in input.geos
 #   (2) HEMCO: Set VERBOSE and WARNINGS to 3 in HEMCO_Config.rc
 #   (3) MAPL ExtData (handles GCHP inputs):
-#         - For root thread (single core) prints set CAP.EXTDATA logger
-#           'root_level' to DEBUG in logging.yml
-#         - For prints by all threads set CAP.EXTDATA logger 'level' to
-#           DEBUG in logging.yml 
+#         - For root thread prints set CAP.EXTDATA logger option 'root_level'
+#           to DEBUG in run directory file logging.yml
+#         - For prints by all threads set CAP.EXTDATA logger option 'level' to
+#           DEBUG in run directory file logging.yml 
 #
 # WARNING: Turning on debug prints significantly slows down the model!
-#          Remember to turn them back off before doing a long simulation.
+#          Remember to turn back off before doing a long simulation.
+
+
+#######################################################
+#    LESS FREQUENTLY CHANGED SETTINGS
+########################################################
+
+#------------------------------------------------
+#    Timesteps
+#------------------------------------------------
+# WARNING: these settings will override settings in input.geos!
+if [[ $CS_RES -lt 180 ]]; then
+    ChemEmiss_Timestep_sec=1200
+    TransConv_Timestep_sec=600
+    TransConv_Timestep_HHMMSS=001000
+else
+    ChemEmiss_Timestep_sec=600
+    TransConv_Timestep_sec=300
+    TransConv_Timestep_HHMMSS=000500
+fi
+RRTMG_Timestep_sec=10800
+# Optimal timesteps are dependent on grid resolution and are automatically
+# set based on the GCHP Working Group's recommendation below. To override
+# these settings, comment out the code and manually define the following
+# variables:
+#    ChemEmiss_Timestep_sec     : chemistry timestep interval [s]
+#    TransConv_Timestep_sec     : dynamic timestep interval [s]
+#    TransConv_Timestep_HHMMSS  : dynamic timestep interval as HHMMSS string
+#
+# NOTE: Default timesteps for c24 and c48, the cubed-sphere rough equivalents
+# of 4x5 and 2x2.5, are the same as defaults timesteps in GEOS-Chem Classic
 
 #------------------------------------------------------------------
 #    Dust mass tuning factor (only if using HEMCO dust extension)
@@ -273,6 +269,39 @@ fi
 # DustDead extension. The mass tuning factor is resolution-dependent and must
 # be defined here for the target resolution if using online dust.
 # NOTE: the online dust extension is NOT recommended for use in GCHP
+
+#------------------------------------------------
+#   Domain decomposition
+#------------------------------------------------
+NXNY_AUTO=ON
+NX=1 # Ignore if NXNY_AUTO=ON
+NY=6 # Ignore if NXNY_AUTO=ON
+# Cores are distributed across each of the six cubed sphere faces using
+# configurable parameters NX and NY. Each face is divided into NX by NY/6
+# regions and each of those regions is processed by a single core 
+# independent of which node it belongs to. Making NX by NY/6 as square
+# as possible reduces communication overhead in GCHP.
+#
+# Set NXNY_AUTO to either auto-calculate NX and NY (ON) (recommended)
+# or set them manually (OFF).
+
+# Rules and tips for setting NX and NY manually (NXNY_AUTO=OFF):
+#   1. NY must be an integer and a multiple of 6	  
+#   2. NX*NY must equal total number of cores (NUM_NODES*NUM_CORES_PER_NODE)
+#   3. Choose NX and NY to optimize NX x NY/6 squareness 
+#         Good examples: (NX=4,NY=24)  -> 96  cores at 4x4
+#                        (NX=6,NY=24)  -> 144 cores at 6x4
+#         Bad examples:  (NX=8,NY=12)  -> 96  cores at 8x2
+#                        (NX=12,NY=12) -> 144 cores at 12x2
+#   4. Domain decomposition requires that CS_RES/NX >= 4 and CS_RES*6/NY >= 4,
+#      which puts an upper limit on total cores per grid resolution.
+#         c24: 216 cores   (NX=6,  NY=36 )
+#         c48: 864 cores   (NX=12, NY=72 )
+#         c90: 3174 cores  (NX=22, NY=132)
+#        c180: 12150 cores (NX=45, NY=270)
+#        c360: 48600 cores (NX=90, NY=540)
+#      Using fewer cores may still trigger a domain decomposition error, e.g.:
+#         c48: 768 cores   (NX=16, NY=48)  --> 48/16=3 will trigger FV3 error
 
 ##########################################################
 ##########################################################
@@ -659,24 +688,30 @@ else
 fi
 
 #### Set output frequency, duration, and mode
-print_msg " "
-print_msg "Diagnostics:"
-print_msg "------------"
-
-if [[ ${#timeAvg_collections[@]} > 0 ]]; then
-   for c in ${timeAvg_collections[@]}; do
-      replace_val $c.mode        "'time-averaged'"  HISTORY.rc
-      replace_val $c.monthly     ${timeAvg_monthly} HISTORY.rc  
-      replace_val $c.frequency   ${timeAvg_freq}    HISTORY.rc
-      replace_val $c.duration    ${timeAvg_dur}     HISTORY.rc
-   done
-fi
-if [[ ${#inst_collections[@]} > 0 ]]; then
-   for c in ${inst_collections[@]}; do
-      replace_val $c.mode        "'instantaneous'" HISTORY.rc
-      replace_val $c.frequency   ${inst_freq}      HISTORY.rc  
-      replace_val $c.duration    ${inst_dur}       HISTORY.rc
-   done
+if [[ ${AutoUpdate_Diagnostics} == "ON" ]]; then
+   print_msg " "
+   print_msg "Diagnostics:"
+   print_msg "------------"
+   if [[ ${#timeAvg_collections[@]} > 0 ]]; then
+      for c in ${timeAvg_collections[@]}; do
+         replace_val $c.mode        "'time-averaged'"  HISTORY.rc
+         replace_val $c.monthly     ${timeAvg_monthly} HISTORY.rc  
+         replace_val $c.frequency   ${timeAvg_freq}    HISTORY.rc
+         replace_val $c.duration    ${timeAvg_dur}     HISTORY.rc
+      done
+   fi
+   if [[ ${#inst_collections[@]} > 0 ]]; then
+      for c in ${inst_collections[@]}; do
+         replace_val $c.mode        "'instantaneous'" HISTORY.rc
+         replace_val $c.frequency   ${inst_freq}      HISTORY.rc  
+         replace_val $c.duration    ${inst_dur}       HISTORY.rc
+      done
+   fi
+elif [[ ${Periodic_Checkpoint} == "OFF" ]]; then
+    print_msg "WARNING: Auto-update of diagnostic settings in HISTORY.rc is turned off"
+else
+    print_msg "ERROR: unknown setting for AutoUpdate_Diagnostics. Must be ON or OFF."
+    exit 1
 fi
 
 
