Changed ExtNr for DustL23M to 125 in setCommonRunSettings.template
run/GCHP/setCommonRunSettings.template
- Changed the search string from 105 to 125 for DustL23M, so that
  it will replace the mass tuning factor with the proper value.

Signed-off-by: Bob Yantosca <yantosca@seas.harvard.edu>

diff --git a/run/GCHP/setCommonRunSettings.sh.template b/run/GCHP/setCommonRunSettings.sh.template
--- a/run/GCHP/setCommonRunSettings.sh.template
+++ b/run/GCHP/setCommonRunSettings.sh.template
@@ -217,7 +217,7 @@ tomasDustDead=""
 Dust_SF=""
 
 # Check if DustL23M is turned on
-result=$(grep "105.*DustL23M" HEMCO_Config.rc || echo "missing")
+result=$(grep "125.*DustL23M" HEMCO_Config.rc || echo "missing")
 if [[ "x${result}" != "xmissing" ]]; then
     array=(${result// / })
     dustL23M=${array[3]}
