Streamline dust tuning factor section of setCommonRunSettings.sh
run/GCHP/setCommonRunSettings.sh
- Define dustDead and tomasDustDead variables to hold "on/off" settings
- Fold 2 separate sections into a single sectino
- Update error messages
- Updated comments
- Update if statement where HEMCO_Config.rc is touched

Signed-off-by: Bob Yantosca <yantosca@seas.harvard.edu>

diff --git a/run/GCHP/setCommonRunSettings.sh.template b/run/GCHP/setCommonRunSettings.sh.template
--- a/run/GCHP/setCommonRunSettings.sh.template
+++ b/run/GCHP/setCommonRunSettings.sh.template
@@ -209,106 +209,62 @@ RRTMG_Timestep_sec=10800
 #    ONLINE DUST MASS TUNING FACTOR
 #------------------------------------------------------------------
 # Mass tuning factor is used in the HEMCO DustDead extenstion for GEOS-Chem
-# benchmarking and is resolution-dependent. We recommend using offline dust
-# instead of the online extension for GCHP science runs.
-#
-# NOTE: We have retuned the dust scaling factors to account for the
-# fact that the HEMCO DustDead extension uses USTAR directly from the
-# meteorology instead of computing it from U10M and V10M.  For now we
-# have computed new scale factors for C24 to allow benchmarks to proceed.
-# Other resolution/met field combinations will be added later.
-#   -- Bob Yantosca (05 Feb 2025)
+# benchmarking and is resolution and met-source dependent. We recommend
+# using offline dust instead of the online extension for GCHP science runs.
 
-metField=$(grep "met_field:" geoschem_config.yml)
-metField=${metField/met_field\:/}
-metField=${metField// /}
-
-errorMsg="Dust scale factor not defined for ${CS_RES} with met field "
-errorMsg+="${metField}. Please add the tuning factor you wish to use "
-errorMsg+="for the target resolution above."
-
-dustEntry=$(grep "105.*DustDead" HEMCO_Config.rc || echo "missing")
-if [[ ${dustEntry} != "missing" ]]; then
-    dustSetting=(${dustEntry// / })
-    if [[ ${dustSetting[3]} = "on" ]]; then
-        if [[ ${STRETCH_GRID} == 'ON' ]]; then
-            echo "WARNING: Online dust (DustDead) is not recommended for stretched-grid simulation. Consider using OFFLINE_DUST."
-        fi
-        if [[ $CS_RES -eq 24 ]]; then
-	    if [[ "x${metField}" == "xMERRA2" ]]; then
-		Dust_SF=5.4856e-5
-	    elif [[ "x${metField}" == "xGEOSFP" ]]; then
-		Dust_SF=4.6495e-5
-	    elif [[ "x${metField}" == "xGEOSIT" ]]; then
-		Dust_SF=3.7410e-5
-	    else
-		echo "${errorMsg}"
-		exit 1
-	    fi
-        elif [[ $CS_RES -eq 30 ]]; then	    
-	    Dust_SF=5.76e-4 # approximated as linear interpolation between 24 and 48. use for testing only!
-	elif [[ $CS_RES -eq 48 ]]; then
-            Dust_SF=5.0416e-4
-        elif [[ $CS_RES -eq 90 ]]; then
-            Dust_SF=4.0e-4
-        elif [[ $CS_RES -eq 180 ]]; then
-            Dust_SF=3.23e-4
-        elif [[ $CS_RES -eq 360 ]]; then
-            Dust_SF=2.35e-4
-        elif [[ $CS_RES -eq 720 ]]; then
-            Dust_SF=2.3e-4
-        else
-            echo "Dust scale factor not defined for this resolution. Please add the tuning factor you wish to use for the target resolution above."
-            exit 1
-        fi
-    fi
+result=$(grep "105.*DustDead" HEMCO_Config.rc || echo "missing")
+if [[ "x${result}" != "xmissing" ]]; then
+    array=(${result// / })
+    dustDead=${array[3]}
 fi
-#------------------------------------------------------------------
-#    ONLINE DUST MASS TUNING FACTOR (for TOMAS)
-#------------------------------------------------------------------
-# Mass tuning factor is used in the HEMCO DustDead extenstion for GEOS-Chem
-# benchmarking and is resolution-dependent. We recommend using offline dust
-# instead of the online extension for GCHP science runs.
-#
-# NOTE: We have retuned the dust scaling factors to account for the
-# fact that the HEMCO DustDead extension uses USTAR directly from the
-# meteorology instead of computing it from U10M and V10M.  For now we
-# have computed new scale factors for C24 to allow benchmarks to proceed.
-# Other resolution/met field combinations will be added later.
-#   -- Bob Yantosca (05 Feb 2025)
+result=$(grep "131.*TOMAS_DustDead" HEMCO_Config.rc || echo "missing")
+if [[ "x${result}" != "xmissing" ]]; then
+    array=(${result// / })
+    tomasDustDead=${array[3]}
+fi
 
-TomasDustEntry=$(grep "131.*TOMAS_DustDead" HEMCO_Config.rc || echo "missing")
-if [[ ${TomasDustEntry} != "missing" ]]; then
-    TomasDustSetting=(${TomasDustEntry// / })
-    if [[ ${TomasDustSetting[3]} = "on" ]]; then
-        if [[ ${STRETCH_GRID} == 'ON' ]]; then
-            echo "WARNING: Online dust (TOMAS_DustDead) is not recommended for stretched-grid simulation. Consider using OFFLINE_DUST."
-        fi
-        if [[ $CS_RES -eq 24 ]]; then
-	    if [[ "x${metField}" == "xMERRA2" ]]; then
-		TomasDust_SF=5.4856e-5
-	    elif [[ "x${metField}" == "xGEOSFP" ]]; then
-		TomasDust_SF=4.6495e-5
-	    elif [[ "x${metField}" == "xGEOSIT" ]]; then
-		TomasDust_SF=3.7410e-5
-	    else
-		echo "${errorMsg}"
-		exit 1
-	    fi
-        elif [[ $CS_RES -eq 48 ]]; then
-            TomasDust_SF=5.0416e-4
-        elif [[ $CS_RES -eq 90 ]]; then
-            TomasDust_SF=4.0e-4
-        elif [[ $CS_RES -eq 180 ]]; then
-            TomasDust_SF=3.23e-4
-        elif [[ $CS_RES -eq 360 ]]; then
-            TomasDust_SF=2.35e-4
-        elif [[ $CS_RES -eq 720 ]]; then
-            TomasDust_SF=2.3e-4
-        else
-            echo "Dust scale factor not defined for this resolution. Please add the tuning factor you wish to use for the target resolution above."
-            exit 1
-        fi
+if [[ "x${dustDead}" == "xon" || "x${tomasDustDead}" == "xon" ]]; then
+    metField=$(grep "met_field:" geoschem_config.yml)
+    metField=${metField/met_field\:/}
+    metField=${metField// /}
+
+    if [[ "x${STRETCH_GRID}" == "xON" ]]; then
+	msg="WARNING: Online dust is not recommended for stretched-grid "
+	msg+="simulations. Consider using OFFLINE_DUST instead."
+	echo "${msg}"
+    fi
+
+    if [[ $CS_RES -eq 24 ]]; then
+	if [[ "x${metField}" == "xMERRA2" ]]; then
+	    Dust_SF=5.4856e-5
+	elif [[ "x${metField}" == "xGEOSFP" ]]; then
+	    Dust_SF=4.6495e-5
+	elif [[ "x${metField}" == "xGEOSIT" ]]; then
+	    Dust_SF=3.7410e-5
+	else
+	    msg="Dust scale factors are currenlty only available for C24. "
+	    msg+="with MERRA-2, GEOSFP, or GEOSIT."
+	    echo "${msg}"
+	    exit 1
+	fi
+    elif [[ $CS_RES -eq 30 ]]; then
+	Dust_SF=5.76e-4 # approximated as linear interpolation between 24 and 48. use for testing only!
+    elif [[ $CS_RES -eq 48 ]]; then
+        Dust_SF=5.0416e-4
+    elif [[ $CS_RES -eq 90 ]]; then
+        Dust_SF=4.0e-4
+    elif [[ $CS_RES -eq 180 ]]; then
+        Dust_SF=3.23e-4
+    elif [[ $CS_RES -eq 360 ]]; then
+        Dust_SF=2.35e-4
+    elif [[ $CS_RES -eq 720 ]]; then
+        Dust_SF=2.3e-4
+    else
+	msg="Dust scale factor not defined for this resolution. Please add "
+	msg+="the tuning factor you wish to use for the target resolution "
+	msg+="above."
+	echo "${msg}"
+        exit 1
     fi
 fi
 
@@ -717,11 +673,8 @@ replace_val      "AdvCore_Advection" "${ADVCORE_ADVECTION}" GCHP.rc
 print_msg ""
 print_msg "HEMCO settings:"
 print_msg "---------------"
-if [[ ${dustSetting[3]} = "on" ]]; then
+if [[ "x${dustDead}" ==  "xon" || "x${tomasDustDead}" == "xon" ]]; then
     replace_val "--> Mass tuning factor" ${Dust_SF} HEMCO_Config.rc
-fi
-if [[ ${TomasDustSetting[3]} = "on" ]]; then
-    replace_val "--> Mass tuning factor" ${TomasDust_SF} HEMCO_Config.rc
 fi
 
 ###  Set initial restart file options
