Avoid run script exiting early if grepped string not found in config file
Using set -e in run scripts caused early exit for transport tracer
simulation due to grepping DustDead in HEMCO_Config.rc. within
setCommonRunSettings.sh.

Signed-off-by: Lizzie Lundgren <elundgren@seas.harvard.edu>

diff --git a/run/GCHP/setCommonRunSettings.sh.template b/run/GCHP/setCommonRunSettings.sh.template
--- a/run/GCHP/setCommonRunSettings.sh.template
+++ b/run/GCHP/setCommonRunSettings.sh.template
@@ -152,29 +152,29 @@ RRTMG_Timestep_sec=10800
 # Mass tuning factor is used in the HEMCO DustDead extenstion for GEOS-Chem
 # benchmarking and is resolution-dependent. We recommend using offline dust
 # instead of the online extension for GCHP science runs.
-dustEntry=$(grep "105.*DustDead" HEMCO_Config.rc)
-dustSetting=(${dustEntry// / })
-if [[ ${dustSetting[3]} = "on" ]]; then
-    if [[ ${STRETCH_GRID} == 'ON' ]]; then
-        echo "WARNING: Online dust (DustDead) is not recommended for stretched-grid simulation. Consider using OFFLINE_DUST."
-    fi
-
-    if [[ $CS_RES -eq 24 ]]; then
-        Dust_SF=6.0e-4
-    elif [[ $CS_RES -eq 48 ]]; then
-        Dust_SF=5.0416e-4
-    elif [[ $CS_RES -eq 90 ]]; then
-        Dust_SF=4.0e-4
-    elif [[ $CS_RES -eq 180 ]]; then
-        Dust_SF=3.23e-4
-    elif [[ $CS_RES -eq 360 ]]; then
-        Dust_SF=2.35e-4
-    elif [[ $CS_RES -eq 720 ]]; then
-        Dust_SF=2.3e-4
-    else
-        echo "Dust scale factor not defined for this resolution. Please add the tuning factor you wish to use for the targe\
-t resolution above."
-        exit 1
+dustEntry=$(grep "105.*DustDead" HEMCO_Config.rc || echo "missing")
+if [[ ${dustEntry} != "missing" ]]; then
+    dustSetting=(${dustEntry// / })
+    if [[ ${dustSetting[3]} = "on" ]]; then
+        if [[ ${STRETCH_GRID} == 'ON' ]]; then
+            echo "WARNING: Online dust (DustDead) is not recommended for stretched-grid simulation. Consider using OFFLINE_DUST."
+        fi
+        if [[ $CS_RES -eq 24 ]]; then
+            Dust_SF=6.0e-4
+        elif [[ $CS_RES -eq 48 ]]; then
+            Dust_SF=5.0416e-4
+        elif [[ $CS_RES -eq 90 ]]; then
+            Dust_SF=4.0e-4
+        elif [[ $CS_RES -eq 180 ]]; then
+            Dust_SF=3.23e-4
+        elif [[ $CS_RES -eq 360 ]]; then
+            Dust_SF=2.35e-4
+        elif [[ $CS_RES -eq 720 ]]; then
+            Dust_SF=2.3e-4
+        else
+            echo "Dust scale factor not defined for this resolution. Please add the tuning factor you wish to use for the target resolution above."
+            exit 1
+        fi
     fi
 fi
 
